version: "3.7"
services:
  app:
    image: ghcr.io/${GITHUB_ACTOR}/tcp-fastapi-server:latest
    container_name: docker-fastapi-deploy-server
    ports:
      - 33333:33333
    networks:
      - app

networks:
  app:
    driver: bridge
